# Generated by Django 3.2.9 on 2021-11-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('type', models.CharField(choices=[('IND', 'Individual'), ('TWIN', 'Twin'), ('DOUB', 'Doubble'), ('TRIP', 'Triple'), ('QUAD', 'Quadruple'), ('ROOM', 'Entire Room')], max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
    ]
