# Generated by Django 3.2.9 on 2021-11-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('type', models.CharField(choices=[('IND', 'Individual'), ('TWIN', 'Twin'), ('DOUB', 'Doubble'), ('TRIP', 'Triple'), ('QUAD', 'Quadruple'), ('ROOM', 'Entire Room')], max_length=20)),
                ('availability', models.BooleanField(default=True)),
                ('price', models.FloatField()),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
            ],
        ),
    ]
